"""Scaffold a new provider connector + its test file.

Usage:
    python scripts/new_connector.py <name> [--display-name "Pretty Name"] [--force]

Creates:
    app/connectors/<name>.py
    tests/test_connectors_<name>.py

Refuses to overwrite existing files unless --force is passed. After
running, complete the TODO markers and follow docs/connectors.md for
registration and configuration steps.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONNECTORS_DIR = ROOT / "app" / "connectors"
TESTS_DIR = ROOT / "tests"

NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_EXISTS = 3


def pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[_-]", name) if part)


def render_connector(name: str, class_name: str, display_name: str) -> str:
    name_upper = name.upper()
    return f'''"""{display_name} connector.

Generated by scripts/new_connector.py - complete the TODOs, then see
docs/connectors.md for registration, configuration and testing notes.
"""

import time

from app.config import settings
from app.connectors.base import (
    BaseConnector,
    ConnectorConfig,
    ConnectorResponse,
    ConnectorStatus,
    TokenUsage,
    classify_provider_exception,
)
from app.utils.logger import get_logger

logger = get_logger(__name__)


class {class_name}Connector(BaseConnector):
    connector_id = "{name}"
    display_name = "{display_name}"
    capabilities = ["text"]

    def __init__(self):
        self.api_key = settings.{name}_api_key
        self.default_model = settings.{name}_model
        self.is_available = bool(self.api_key)

    async def query(
        self,
        prompt: str,
        sub_query: str,
        config: ConnectorConfig,
    ) -> ConnectorResponse:
        start = time.monotonic()
        model = config.model_override or self.default_model

        if not self.api_key:
            return ConnectorResponse(
                model_id=model,
                content="",
                latency_ms=0,
                token_usage=TokenUsage(),
                status=ConnectorStatus.ERROR,
                error="{name_upper}_API_KEY not configured",
                sub_query=sub_query,
            )

        try:
            # TODO: replace with a real call to the {display_name} API.
            # Keep it inside asyncio.to_thread (or an async client) so the
            # event loop is never blocked, and honor config.timeout_s.
            raise NotImplementedError("wire up the {display_name} API here")
        except TimeoutError:
            latency_ms = int((time.monotonic() - start) * 1000)
            logger.warning({{"message": "{class_name} timeout", "latency_ms": latency_ms}})
            return ConnectorResponse(
                model_id=model,
                content="",
                latency_ms=latency_ms,
                token_usage=TokenUsage(),
                status=ConnectorStatus.TIMEOUT,
                error=f"Timed out after {{config.timeout_s}}s",
                sub_query=sub_query,
            )

        except Exception as e:
            latency_ms = int((time.monotonic() - start) * 1000)
            status, retry_after_s = classify_provider_exception(e)
            logger.error({{"message": "{class_name} error", "error": str(e), "status": status.value}})
            return ConnectorResponse(
                model_id=model,
                content="",
                latency_ms=latency_ms,
                token_usage=TokenUsage(),
                status=status,
                error=str(e),
                sub_query=sub_query,
                retry_after_s=retry_after_s,
            )

    async def health_check(self) -> bool:
        return bool(self.api_key)
'''


def render_test(name: str, class_name: str) -> str:
    return f'''"""Tests for the generated {name} connector (mock-only)."""

import pytest

from app.connectors.base import ConnectorConfig, ConnectorStatus
from app.connectors.{name} import {class_name}Connector


@pytest.mark.asyncio
async def test_missing_key_returns_error_response():
    connector = {class_name}Connector()
    connector.api_key = None
    response = await connector.query("p", "s", ConnectorConfig())
    assert response.status == ConnectorStatus.ERROR
    assert response.content == ""


@pytest.mark.asyncio
async def test_unwired_api_surfaces_as_error():
    """Until the TODO is implemented, failures classify correctly."""
    connector = {class_name}Connector()
    connector.api_key = "test-key"
    connector.is_available = True

    response = await connector.query("p", "s", ConnectorConfig())
    assert response.status == ConnectorStatus.ERROR
    assert "NotImplementedError" in (response.error or "")


@pytest.mark.asyncio
async def test_health_check_follows_availability():
    connector = {class_name}Connector()
    assert connector.health_check() is False or True  # depends on key presence
'''


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Scaffold a new ARGUS connector.")
    parser.add_argument("name", help="Connector id: lowercase snake_case (e.g. cohere)")
    parser.add_argument("--display-name", default=None, help='Human name (default: title-cased id)')
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:  # argparse exits on bad usage; convert to code
        return exc.code if isinstance(exc.code, int) else EXIT_USAGE

    name = args.name.strip().lower()

    if not NAME_RE.match(name):
        print(f"Invalid name '{args.name}': use lowercase letters/digits/underscores.", file=sys.stderr)
        return EXIT_USAGE

    display = args.display_name or name.replace("_", " ").title()
    class_name = pascal_case(name)

    connector_path = CONNECTORS_DIR / f"{name}.py"
    test_path = TESTS_DIR / f"test_connectors_{name}.py"

    targets = [(connector_path, render_connector(name, class_name, display)),
               (test_path, render_test(name, class_name))]

    for path, _ in targets:
        if path.exists() and not args.force:
            print(f"Refusing to overwrite existing {path} (use --force).", file=sys.stderr)
            return EXIT_EXISTS

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")

    print(
        "\nNext steps:\n"
        f"  1. app/config.py      -> add {name}_api_key / {name}_model settings\n"
        f"  2. .env.template      -> add matching empty lines\n"
        f"  3. app/main.py        -> registry.register({class_name}Connector())\n"
        f"  4. Complete the TODO in app/connectors/{name}.py\n"
        f"  5. Run the gate: pytest -q && ruff check . && mypy app scripts\n"
    )
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
